# Site settings

title: IFixPhones
email: ifixphonesgenius.gmail.com
description: "Where your life is back"


# Build settings

markdown: kramdown
permalink: pretty

port: 8080

sass:
  sass_dir: assets/css
  style: :nested
