#-------------------------------
# General Site Settings

title: IFixPhones
email: support@ifixphonesgenius.com
description: "Where your life is back"

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Home, url: '#'}
- {name: About, url: '#about'}
- {name: Services, url: '#services'}
- {name: Location, url: '#'}
- {name: Contact, url: '#contact'}

#-------------  ABOUT -------------


#-------------  SERVICES -------------
services:
- {name: iPhones, folder: 'iphone', file: 'service/iphone.html', model: "3G\n3GS\n4\n4S\n5\n5S\n6\n6Plus"}
- {name: Android Phone, folder: 'androidphone', file: 'service/androidphone.html', model: "Samsung\nHTC\nNexus\nMotorolla"}
- {name: iPad, folder: 'ipad',  file: 'service/ipad.html', model: "iPad 1-4\niPad Mini"}
- {name: Tablet, folder: 'tablet', file: 'service/tablet.html', model: "Dell\nNexus\nSurface\nGalaxy Tab"}


#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'http://twitter.com/ifixphones'}
- {icon: 'facebook', link: 'https://facebook.com/ifixphones'}
- {icon: 'linkedin', link: 'https://linkedin.com/ifixphones'}
