#-------------------------------
# General Site Settings

title: IFixPhones
email: support@ifixphonesgenius.com
description: "Where your life is back"

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Home, url: '#'}
- {name: About, url: '#about'}
- {name: Services, url: '#services'}
- {name: Location, url: '#'}
- {name: Contact, url: '#contact'}

#-------------  SERVICES -------------
services:
- {name: iPhones, folder: 'iphone', image: 'iPhone.jpeg', file: 'service/iphone.html' }
- {name: Android Phone, folder: 'androidphone', image: 'and-phone.jpg', file: 'service/androidphone.html'}
- {name: iPad, folder: 'ipad', image: 'ipad.jpg', file: 'service/ipad.html'}
- {name: Tablet, folder: 'tablet', image: 'tablet.jpg', file: 'service/tablet.html'}

#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'http://twitter.com/ifixphones'}
- {icon: 'facebook', link: 'https://facebook.com/ifixphones'}
- {icon: 'linkedin', link: 'https://linkedin.com/ifixphones'}