#-------------  SERVICES -------------
services:
- {name: iPhones Repairs- <br> cracked screens <br> OS upgrades, repair: iPhones Repairs, image: 'iPhone.jpeg'}
- {name: Android Phone, repair: Android Phones Repair, image: 'and-phone.jpg'}
- {name: iPad, repair: iPadRepair, image: 'ipad.jpg'}
- {name: Tablet, repair: Tablets Repair, image: 'tablet.jpg'}